version: '3.7'

services:
  python:
    container_name: python
    image: ./backend
    ports:
      - "80:80"
    volumes:
      - ./backend:/myway

  neo4j:
    image: neo4j:5.21.0-enterprise
    container_name: neo4j
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    restart: always
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    environment:
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
